// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package wallet

import (
	"context"

	"wallet-srv/wallet_srv"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WalletsReq  = wallet_srv.WalletsReq
	WalletsResp = wallet_srv.WalletsResp

	Wallet interface {
		Wallets(ctx context.Context, in *WalletsReq, opts ...grpc.CallOption) (*WalletsResp, error)
	}

	defaultWallet struct {
		cli zrpc.Client
	}
)

func NewWallet(cli zrpc.Client) Wallet {
	return &defaultWallet{
		cli: cli,
	}
}

func (m *defaultWallet) Wallets(ctx context.Context, in *WalletsReq, opts ...grpc.CallOption) (*WalletsResp, error) {
	client := wallet_srv.NewWalletClient(m.cli.Conn())
	return client.Wallets(ctx, in, opts...)
}
