// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package server

import (
	"context"

	"wallet-srv/internal/logic"
	"wallet-srv/internal/svc"
	"wallet-srv/wallet_srv"
)

type WalletServer struct {
	svcCtx *svc.ServiceContext
	wallet_srv.UnimplementedWalletServer
}

func NewWalletServer(svcCtx *svc.ServiceContext) *WalletServer {
	return &WalletServer{
		svcCtx: svcCtx,
	}
}

func (s *WalletServer) Wallets(ctx context.Context, in *wallet_srv.WalletsReq) (*wallet_srv.WalletsResp, error) {
	l := logic.NewWalletsLogic(ctx, s.svcCtx)
	return l.Wallets(in)
}

func (s *WalletServer) WalletsByID(ctx context.Context, in *wallet_srv.WalletsByIDReq) (*wallet_srv.WalletsByIDResp, error) {
	l := logic.NewWalletsByIDLogic(ctx, s.svcCtx)
	return l.WalletsByID(in)
}

func (s *WalletServer) Transfer(ctx context.Context, in *wallet_srv.TransferReq) (*wallet_srv.TransferResp, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}
